### ISSUE TITLE
unable to build due to ghc missing support for armv7

### ISSUE THREAD

**Issue by Fuseteam** [thefloweringash/thefloweringash-armv7#1] opened 2020-11-17 13:26 UTC
i was attempting to get things to build for armhf but no matter what ghc complains about not supporting armhf

**Comment by thefloweringash** [comment] 2020-11-19 13:45
Hello,

I think you might be looking in the wrong place. This repository doesn't really do anything interesting. If this is a problem with nixpkgs, you'd be better to [open an issue there][nixpkgs-new-issue]. I note that GHC has [binary releases for armv7][ghc-armv7], so it should be possible to make this work. Sorry it's not clear from your message what environment you're working with, if it's not nixpkgs you should probably file an issue on your particular distribution's issue tracker.

Going to close this, since there's not much I can do here.

[nixpkgs-new-issue]: https://github.com/NixOS/nixpkgs/issues/new/choose
[ghc-armv7]: https://www.haskell.org/ghc/download_ghc_8_10_2.html#linux_armv7

**Closed as completed by thefloweringash** 2020-11-19 13:45 UTC

**Comment by Fuseteam** [comment] 2020-11-19 19:43
@thefloweringash i am attempting to build nixpkgs on armv7, which nixpkgs doesn't officially support. i first attempted to use [your cachix](https://app.cachix.org/cache/thefloweringash-armv7), but noticed things weren't building correctly on [your hydra instance](https://hydra.cons.org.nz/project/thefloweringash-armv7) and i believe it has to do with ghc complaining about armv7 for some reason. This repo is the closest i could find to both of those. my enviroment is just an bq e5 phone on which i want to install nixpkgs

btw i'm not trying to attack you i'm just trying to explain as much as i can what my goal/problem is

**Comment by thefloweringash** [comment] 2020-11-21 08:39
> @thefloweringash i am attempting to build nixpkgs on armv7, which nixpkgs doesn't officially support. i first attempted to use [your cachix](https://app.cachix.org/cache/thefloweringash-armv7), but noticed things weren't building correctly on [your hydra instance](https://hydra.cons.org.nz/project/thefloweringash-armv7) and i believe it has to do with ghc complaining about armv7 for some reason. This repo is the closest i could find to both of those. my enviroment is just an bq e5 phone on which i want to install nixpkgs

Even though nixpkgs doesn't officially support armv7l-linux, or have a cache for it, the project will accept fixes. The `#nixos-aarch64` channel on freenode also contains people interested in armv7l-linux.

Support for ghc on armv7l-linux was added recently via https://github.com/NixOS/nixpkgs/pull/98656. If you're having problems, opening an issue and mentioning the author (@sorki) is probably the best thing to do. I took a quick look, and it seems like the problem is that the bootstrap packages for the current default `ghc` version don't support 32-bit arm, which might be fixed by (untested):
```diff
diff --git a/pkgs/top-level/haskell-packages.nix b/pkgs/top-level/haskell-packages.nix
index e613b931d63..2d25ea149a9 100644
--- a/pkgs/top-level/haskell-packages.nix
+++ b/pkgs/top-level/haskell-packages.nix
@@ -96,7 +96,7 @@ in {
     };
     ghc8102 = callPackage ../development/compilers/ghc/8.10.2.nix {
       # aarch64 ghc865Binary gets SEGVs due to haskell#15449 or similar
-      bootPkgs = if stdenv.isAarch64 then
+      bootPkgs = if stdenv.isAarch64 || stdenv.isAarch32 then
           packages.ghc8102BinaryMinimal
         else
           packages.ghc865Binary;
```

As for my hydra, I think it's currently suffering from issues that would be fixed by https://github.com/NixOS/hydra/pull/832 and  https://github.com/NixOS/nixpkgs/pull/103925. I'll add a review for the latter shortly.

> btw i'm not trying to attack you i'm just trying to explain as much as i can what my goal/problem is

All good. I was worried about seeming rude. Tone is hard on the internet :-)

**Comment by sorki** [comment] 2020-11-21 12:51
You can either use `ghc8102Binary` on `armv7l` directly (via `haskell.packages.ghc8102Binary.<...>`) or you can use it as bootstrap compiler for other GHC versions. For example I've used it boot native `ghc8102` like so:

```
     ghc8102 = callPackage ../development/compilers/ghc/8.10.2.nix {
-      bootPkgs = packages.ghc865Binary;
+      bootPkgs = packages.ghc8102Binary;
```

It's also used to bootstrap `ghc884` on 64 bit arm currently.  Suggestion by @thefloweringash looks good and can be probably proposed as a PR to nixpkgs.

**Comment by Fuseteam** [comment] 2020-11-21 19:08
> All good. I was worried about seeming rude. Tone is hard on the internet :-)

haha true thanks for explaination and pointers i check to see what i can do



> You can either use `ghc8102Binary` on `armv7l` directly (via `haskell.packages.ghc8102Binary.<...>`) or you can use it as bootstrap compiler for other GHC versions. For example I've used it boot native `ghc8102` like so:
> 
> ```
>      ghc8102 = callPackage ../development/compilers/ghc/8.10.2.nix {
> -      bootPkgs = packages.ghc865Binary;
> +      bootPkgs = packages.ghc8102Binary;
> ```
> 
> It's also used to bootstrap `ghc884` on 64 bit arm currently. Suggestion by @thefloweringash looks good and can be probably proposed as a PR to nixpkgs.

cool thank you i'll check it out, any reccomendations on how i can test it?

**Comment by Fuseteam** [comment] 2020-12-11 13:31
@thefloweringash weirdly enough all package are failing after the pr that fixed it at first was merged
